version: '3.8'

services:
  db:
    image: postgres:14
    env_file: .env
    ports: 
      - "5432:5432"
    volumes:
      - THEWINNERS_3308:/var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d

  web:
    image: node:lts
    working_dir: /home/node/app
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    command: ["npm", "start"]

volumes:
  THEWINNERS_3308:
